// vue3-tsx/src/views/Review/index.tsx
import styles from "./index.module.less";
import { ApiGetReviewTodoList, ApiDeleteTodoToRecycle } from "@/api/todo";
import { defineComponent } from 'vue';

export default defineComponent({
  name: "Review",
  data() {
    return {
      todoList: [],
      loading: false,
      visible: false,
      todoDetail: {},
      taskData: {}
    };
  },
  computed: {
    ratioText() {
      const { rate } = this.taskData;
      if (rate <= 3) {
        return "低";
      } else if (rate <= 4) {
        return "中";
      }
      return "高";
    }
  },
  methods: {
    async getReviewTodoList() {
      this.loading = true;
      const resp = await ApiGetReviewTodoList();
      this.loading = false;
      if (resp.code === 0) {
        this.taskData = resp.result.task;
        this.todoList = resp.result.list;
      }
    },
    handleCheck(item) {
      const { id, isFinished } = item;
      this.todoList = this.todoList.filter(todo => todo.id !== id);
      if (isFinished) {
        this.todoList.push(item);
      } else {
        this.todoList.unshift(item);
      }
    },
    handleGoDetail(item) {
      this.$router.push({
        name: "TodoDetailView",
        params: {
          id: item.id
        }
      });
    },
    handleUpdate({ visible }) {
      this.visible = visible;
    },
    async handleDelete(item) {
      const { id } = item;
      const resp = await ApiDeleteTodoToRecycle(id);
      if (resp.code === 0) {
        this.$toast.success("删除成功");
        this.todoList = this.todoList.filter(todo => todo.id !== id);
      }
    }
  },
  mounted() {
    this.getReviewTodoList();
  },
  render() {
    const { todoList, taskData, loading } = this.$data;

    return (
      <EContainer>
        <EHeader title={this.$route.meta.title} type="menu" />
        <EAside />
        <EContent>
          <div class={styles.reviewHeader}>
            <div class={styles.rateBox}>
              <van-rate
                value={taskData.rate}
                color="#f5222d"
                allowHalf={true}
              />
            </div>
            <div class={styles.reviewBox}>
              <div class={styles.reviewBoxItem}>
                本周完成：<span>{taskData.finishCount}</span>
              </div>
              <div class={styles.reviewBoxItem}>
                本周评分：{taskData.rate && <span>{taskData.rate}星</span>}
              </div>
              <div class={styles.reviewBoxItem}>
                本周效率：{taskData.rate && <span>{this.ratioText}</span>}
              </div>
            </div>
          </div>
          <van-divider class="divider">完成任务</van-divider>
          <ETodoCard
            loading={loading}
            todoList={todoList}
            onCheck={this.handleCheck}
            onGoDetail={this.handleGoDetail}
            onDel={this.handleDelete}
          />
        </EContent>
        <EFooter />
      </EContainer>
    );
  }
});

// src/views/Review/index.jsx
export default {
  name: "Review",
  data() {
    return {
      todoList: [],
      visible: false,
      todoDetail: {}
    };
  },
  methods: {
    getTodoList() {
      this.todoList = [
        {
          id: 1,
          title: "这是一段描述文字",
          description: "这是一段描述文字",
          date: "2020-07-04 15:06",
          status: 1,
          isFinished: true
        },
        {
          id: 2,
          title: "这是一段描述文字",
          description: "这是一段描述文字",
          date: "2020-08-03 11:28",
          status: 2,
          isFinished: false
        },
        {
          id: 3,
          title: "这是一段描述文字这是一段描述文字这是一段描述文字",
          description: "这是一段描述文字",
          date: "2020-03-03 19:11",
          status: 2,
          isFinished: false
        },
        {
          id: 4,
          title: "这是一段描述文字这是一段描述文字这是一段描述文字",
          description: "这是一段描述文字",
          date: "2020-07-04 19:11",
          status: 2,
          isFinished: false
        }
      ].sort((a, b) => {
        return b.status - a.status;
      });
    },
    handleCheck(item) {
      const { id, isFinished } = item;
      this.todoList = this.todoList.filter(todo => todo.id !== id);
      if (isFinished) {
        this.todoList.push(item);
      } else {
        this.todoList.unshift(item);
      }
    },
    handleGoDetail(event, item) {
      this.visible = true;
      this.todoDetail = item;
      this.$router.push({
        name: "TodoDetail",
        params: {
          id: item.id
        }
      });
    },
    handleUpdate({ visible }) {
      this.visible = visible;
    }
  },
  mounted() {
    this.getTodoList();
  },
  render() {
    const { todoList, visible, todoDetail } = this.$data;

    return (
      <EContainer>
        <router-view
          visible={visible}
          todo={todoDetail}
          onUpdate={this.handleUpdate}
        />
        <EHeader title={this.$route.meta.title} type="menu" />
        <EAside />
        <EContent>
          <ETodoCard
            todoList={todoList}
            onCheck={this.handleCheck}
            onGoDetail={this.handleGoDetail}
          />
        </EContent>
        <EFooter />
      </EContainer>
    );
  }
};
